[pyprland]
plugins = ["scratchpads", "magnify"]

[scratchpads]

[scratchpads.term]
command = "alacritty --class scratchpad"
margin = 50.0

[scratchpads.ranger]
command = "alacritty --class scratchpad -e ranger"
margin = 50.0

[scratchpads.wego]
command = "alacritty --class scratchpad -e wego"
margin = 50.0

[scratchpads.btm]
command = "alacritty --class scratchpad -e btm"
margin = 50.0
