[pyprland]
plugins = ["scratchpads", "magnify"]

[scratchpads]

[scratchpads.term]
command = "alacritty --class term"
pinnded = "true"
position = "0% 60%"
size = "100% 40%"
class = "term"
animation = "fromBottom"

[scratchpads.org]
command = "emacsclient -server-file org -c ~/stuff/p/org/todo.org"
pinnded = "true"
position = "40% 0%"
size = "60% 100%"
class = "term"
animation = "fromRight"

[scratchpads.ranger]
command = "alacritty --class scratchpad -e ranger"
margin = 50.0

[scratchpads.btm]
command = "alacritty --class scratchpad -e btm"
margin = 50.0
